[package]
name = "db"
version = "0.1.0"
edition = "2024"

[lib]
name = "db"
path = "src/lib.rs"

[dependencies]
mongodb = "3.2.3"
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}