[package]
name = "grpc_service"
version = "0.1.0"
edition = "2024"

[lib]
name = "grpc_service"
path = "src/lib.rs"

[dependencies]
prost = "0.13.5"
tokio = { version = "1.45.1", features = ["full"] }
tonic = "0.13.1"
